# Array Operations

In [2]:
import numpy as np

#### Arithmetic Operation

In [5]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

array([ 6,  7,  8,  9, 10])

**Addition of array having same number of elements**

In [8]:
arr2 = a1 + a2                   #size of both array must be same
arr2

array([ 7,  9, 11, 13, 15])

All the elements having same index added together

**Substraction**  
array having same number of elements

In [10]:
a1 - a2                      #size of both array must be same

array([-5, -5, -5, -5, -5])

similary we can peerform *, /, //, **

#### Broadcasting 

If you have a single number and you want to add (perform any opertion) this number to each element of the array then

In [12]:
l1 = [2,4,5,6,9,10]
arr3 = np.array(l1)
arr3

array([ 2,  4,  5,  6,  9, 10])

adding 10 in each element of arr3

In [14]:
arr3 + 10                              #it is called broadcasting

array([12, 14, 15, 16, 19, 20])

**Performing these in vector**

In [21]:
arr4 = np.arange(1,26).reshape(5,5)
arr4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
arr5 = np.arange(3,28).reshape(5,5)
arr5

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27]])

In [25]:
arr4+arr5

array([[ 4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52]])

Broadcasting in vactor

In [26]:
arr5+10

array([[13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37]])

#### Deep And Shallow Copy

In [29]:
arr6 = np.arange(1,21)
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [36]:
slice = arr6[:5]
slice = slice * 10                   #performed broadcasting in slice and also saved it
slice

array([10, 20, 30, 40, 50])

In [37]:
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])