In [4]:
import numpy as np

**Basic Array Creation**  
We use python list to make array in numpy

In [11]:
arr = np.array([1,2,3,56])
arr     #print arr

array([ 1,  2,  3, 56])

In [14]:
a = [1,23, 45, "hello"]   #its a list we can pass it to numpy to convert it into array

In [15]:
np.array(a)

array(['1', '23', '45', 'hello'], dtype='<U21')

**Above you can see**  
dtype='<u21' it means all the element of the array are converted to unicode format, beacuse array can store homogeneous data types only,
it means if you give a hetrogeneous list then it will convert its data type to string

#### Vectors and Metrices

Vectors are one dimentional, where Metrices are multi-dimentional   
We can store vector in list but for metrices we need row and coloumns which are not supported by lists so we make, multidimensional arrays

In [18]:
l1 = [[1,2,3],[4,5,8],[10,43,56]]
l1

[[1, 2, 3], [4, 5, 8], [10, 43, 56]]

**Above you can see it, it is looking one dimentional**  
Now we will convert it to array

In [19]:
np.array(l1)

array([[ 1,  2,  3],
       [ 4,  5,  8],
       [10, 43, 56]])

*So here we can see that its looking like a metrix*

#### Array Generation Function

##### **np.arange(start, stop, steps)**  
simillar to range function, but here we write arrange

In [22]:
arr1 = np.arange(1,10,2)
arr1

array([1, 3, 5, 7, 9])

##### **Creating Zero/Null metrix**
np.zeros((row, column))

*1D*

In [32]:
arr2 = np.zeros(6)
arr2

array([0., 0., 0., 0., 0., 0.])

*2d*

In [31]:
arr3 = np.zeros((6,6))
arr3

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [33]:
arr3 = np.zeros((4,6))
arr3

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### Ones matrix

In [34]:
arr4 = np.ones(6)
arr4

array([1., 1., 1., 1., 1., 1.])

In [36]:
arr5 = np.ones((3,5))
arr5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])