# Array Operations

In [2]:
import numpy as np

#### Arithmetic Operation

In [5]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

array([ 6,  7,  8,  9, 10])

**Addition of array having same number of elements**

In [8]:
arr2 = a1 + a2                   #size of both array must be same
arr2

array([ 7,  9, 11, 13, 15])

All the elements having same index added together

**Substraction**  
array having same number of elements

In [10]:
a1 - a2                      #size of both array must be same

array([-5, -5, -5, -5, -5])

similary we can perform *, /, //, **

#### Broadcasting 

If you have a single number and you want to add (perform any opertion) this number to each element of the array then

In [12]:
l1 = [2,4,5,6,9,10]
arr3 = np.array(l1)
arr3

array([ 2,  4,  5,  6,  9, 10])

adding 10 in each element of arr3

In [14]:
arr3 + 10                              #it is called broadcasting

array([12, 14, 15, 16, 19, 20])

**Performing these in vector**

In [21]:
arr4 = np.arange(1,26).reshape(5,5)
arr4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
arr5 = np.arange(3,28).reshape(5,5)
arr5

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27]])

In [25]:
arr4+arr5

array([[ 4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52]])

Broadcasting in vactor

In [26]:
arr5+10

array([[13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37]])

#### Deep And Shallow Copy

In [29]:
arr6 = np.arange(1,21)
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [36]:
slice = arr6[:5]
slice = slice * 10                   #performed broadcasting in slice and also saved it
slice

array([10, 20, 30, 40, 50])

In [37]:
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

So here we can see that the changes in slice are not affecting the actual array, but if we change slice of a list then it will also affect the actual list also , That means array makes **Shallow copy** when we slice them and occupy new space for the slice

In [39]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
b=a

In [41]:
b[0] = 99

In [42]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9])

here we can see that the change in **b** also changing the **a**,  
so by b=a they just pass on the locations, **b** will not occupy a new place for him(its a **deep copy**)  
if you want to make a shallow copy then write b = a.copy()

In [44]:
c = np.arange(10,20);
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [45]:
d=c.copy()

In [46]:
d[1] = 77

In [47]:
d

array([10, 77, 12, 13, 14, 15, 16, 17, 18, 19])

In [48]:
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

here you can see there are no changes in **c**

#### Matrix operations

In [49]:
A = np.array([[1, 2],[3, 4]])
B = np.array([[5,6], [7, 8]])

In [50]:
A

array([[1, 2],
       [3, 4]])

In [51]:
B

array([[5, 6],
       [7, 8]])

Simple operations in matrics

In [52]:
 A * B

array([[ 5, 12],
       [21, 32]])

**But here you can see its not proper matrix multiplication**

**For proper matrix multiplication**  
A @ B

In [53]:
A @ B

array([[19, 22],
       [43, 50]])

and we can also do 

In [54]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

**Transpose of Array**  
just write array.T

In [55]:
A.T

array([[1, 3],
       [2, 4]])

#### Advance Array Manipulation

**Stacking Array**

We can stack two arrays(1D, vectors only) only not to matrics 

In [59]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [60]:
np.vstack((a,b))            #it will make vertical stack

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [64]:
np.hstack((a,b))             #it will make horizental stack (two array get joined)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [63]:
np.column_stack((a,b))            #it will make a coloumn stack 

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

**Splitting Array**

In [66]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
np.hsplit(c,2)         #np.hsplit(array, n), it splits array horizentaly in 'n' parts

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

here the number of column should be divisible by 'n'

In [71]:
np.vsplit(c, 2)                  #np.vsplit(array, n),it will do vertical split

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

here the number of row should be divisible by 'n'